### ISSUE TITLE
Files added to Works don't persist

### ISSUE THREAD

**Issue by ggeisler** [projecthydra-labs/hyrax#836] opened 2017-04-25 17:42 UTC
### Descriptive summary

(This _might_ be a duplicate because it appears to be a known issue among team members, but I can't find a specific ticket for it.)

You can add file(s) to a work and they appear to be processed as expected, but when you later edit or display the work, there are no files associated with it.

### Steps to reproduce the behavior

1. Create a work
1. Attach a file
1. Save the work
1. Navigate away from the work
1. Return to edit the work
1. View the Files tab (no longer shows any attached files)

**Comment by jcoyne** [comment] 2017-04-25 17:56
Is this on your local machine? If so have you started the sidekiq workers (or set the jobs to run inline)?

**Comment by ggeisler** [comment] 2017-04-25 18:02
Yes, this is a local dev environment, and no, I didn't start sidekiq workers. I was wondering if there was something I should be starting or configuring that I wasn't (asked that in my Slack message about this). What's the process for doing that (either option)?

If that solves the issue, great. But @hannahfrost said this was an issue known to her, and I believe she is only using the hosted version, so not sure what that implies.

**Comment by jcoyne** [comment] 2017-04-25 21:29
@ggeisler the directions for starting the background workers are here: https://github.com/projecthydra-labs/hyrax#start-background-workers

**Comment by ggeisler** [comment] 2017-04-25 21:39
@jcoyne Yeah, thanks, I already found that and tried setting the jobs to run inline, but now I'm getting this error:

> Unable to execute command "fits.sh -i "/Users/geisler/Sites/stanford/hyrax/.internal_test_app/tmp/uploads/hyrax/uploaded_file/file/4/butterfly.jpg""
sh: fits.sh: command not found

even though the path to fits is listed in my path statement in .bash_profile. Obviously something is not set up correctly, though, so I'm trying to figure out how to troubleshoot...

**Comment by mjgiarlo** [comment] 2017-04-25 22:51
@ggeisler Do you still think this is a Hyrax bug, or maybe a documentation opportunity, or what?

**Comment by ggeisler** [comment] 2017-04-25 23:05
@mjgiarlo No, no bug. Fixed locally and @jcoyne updated the [documentation](https://github.com/projecthydra-labs/hyrax/pull/838) so others will not run into (at least one of) the problems I did.

I don't know if we can confirm the problem is fixed on the hosted version yet, but we can close this when the update is there.

**Comment by mjgiarlo** [comment] 2017-04-25 23:07
@ggeisler I confirmed I can do this in the hosted version about a half-hour ago, as it turns out. Closing!

Thanks, Gary.

**Closed by mjgiarlo** 2017-04-25 23:07 UTC
Labels: feedback needed
