### ISSUE TITLE
When Import Purl Metadata jobs fail due to data validation the operation should be marked as failed but the job should succeed (or at least not returned to the queue)

### ISSUE THREAD

**Issue by bbranan** [projecthydra-labs/hyrax#360] opened 2017-02-03 23:16 UTC
When a worker processes an Import Purl Metadata job, if validation of the data to be imported fails, the operation should be considered a failure and marked as such in the database. Given that we know the data is bad, there is no reason to return the job to the queue and have it fail again for the same reason. This eventually results in the job landing on the dead letter queue. 

As long as the fact that the import failed (for a known reason) is captured as part of the operation output, there is no reason for the job itself to be retried or be pushed to the dead letter queue.

**Comment by jcoyne** [comment] 2017-02-04 01:06
The import purl job is not in this repository. it's in projecthyra-labs/hyku.  In that job all the data is coming from the PURL service, which should always have titles (right @atz?), so if its complaining about missing a title, the true cause is probably something else entirely. Can you please send a logged backtrace of where you are seeing these errors or otherwise let us know how to duplicate this issue?

**Comment by jcoyne** [comment] 2017-02-04 14:30
Duplicate of https://github.com/projecthydra-labs/hyku/issues/621 ?

**Comment by bbranan** [comment] 2017-02-06 14:07
https://github.com/projecthydra-labs/hyku/issues/621 does appear to be the issue that resulted in this ticket being created. While it would be great to fix the source data, the primary purpose of this ticket is to consider how the import job should operate when it encounters input data that is not valid. The assumption here is that we will usually not have control over the source data, so we want to expose validation problems in a way that allows the data owner can resolve them and also have the import function not cycle unnecessarily on known bad data.

If this ticket belongs under the hyku project, I'd be happy to move it there.

**Comment by jcoyne** [comment] 2017-02-06 16:37
@bbranan the Import from purl job is not a general purpose tool. It is specifically used for collecting data from stanford for the purpose of testing the site.  It is not something that anyone will be using in production.

**Comment by mjgiarlo** [comment] 2017-02-06 19:01
Deciding to close this issue since it's a concretion of #358, which is now post-MVP, plus this job is only for Stanford-specific testing.

**Closed by mjgiarlo** 2017-02-06 19:01 UTC
Labels: enhancement, needs feedback
