### ISSUE TITLE
Running the workflow rake task doesn't set the Default workflow in the Default Admin Set 

### ISSUE THREAD

**Issue by bmquinn** [projecthydra-labs/hyrax#897] opened 2017-05-04 18:52 UTC
### Descriptive summary

Ran into an issue during our Sufia 7.3 > Hyrax upgrade. After running `rake curation_concerns:workflow:load` we ran into an issue where the "Default workflow" was not set for the Default Admin Set. Possibly due to an ordering issue, our Admin Set was created prior to loading the workflows if I recall correctly. In the screenshot below, neither option was selected for the Default workflow. This issue was easily solved by checking the radio button for the Default workflow in the admin interface and saving.

### Expected behavior

<img width="958" alt="default_workflow" src="https://cloud.githubusercontent.com/assets/1395707/25719714/f3c289cc-30cf-11e7-9bab-ed37e8d99ed3.png">

**Comment by mjgiarlo** [comment] 2017-05-04 19:33
@bmquinn I'm wondering how I might reproduce this. I tried generating a new Hyrax `1-0-stable` instance and the checkbox is selected. So the issue pops up when you create the Default AS and load works and *then* upgrade to Hyrax? If so, maybe we "fix" this by adding a line to the release notes saying "go to the AS UI and check the box like @bmquinn did?"

**Comment by mjgiarlo** [comment] 2017-05-04 19:39
(Which I've now done.)

**Comment by hackmastera** [comment] 2017-05-05 14:33
I think the fix is to reorder the operations in the README; put the workflow loading rake task before the default admin set task.

However, I believe if you install via template it does the workflow load for you, so in that instance that step would be optional.

**Comment by jcoyne** [comment] 2017-05-05 14:46
@hackmastera can you confirm that and add documentation as to why it has to be that way?

**Comment by mjgiarlo** [comment] 2017-05-15 16:43
@hackmastera Might you have cycles for :point_up:? Alternatively, given the discussion above, I wonder if we might close this issue? cc: @bmquinn

**Comment by hackmastera** [comment] 2017-05-15 20:34
could not reproduce on hyrax 1.0.0.rc2

**Comment by mjgiarlo** [comment] 2017-05-15 20:46
Thx! (Feel free to re-open if closed too hastily.)

**Closed by mjgiarlo** 2017-05-15 20:46 UTC
Labels: bug, collections/admin sets, mediated deposit / workflow, ready
