### ISSUE TITLE
Work type selection modal should gracefully handle n work types

### ISSUE THREAD

**Issue by mjgiarlo** [projecthydra-labs/hyrax#274] opened 2017-01-17 18:52 UTC
Where n = 15-20 types.

Currently the design we're implementing for work type selection (both for single works and for batch works) in advance of creating new works is a modal with styled radio buttons. This works fine for a small number of work types. The design should accommodate up to 20 work types.

**Comment by mjgiarlo** [comment] 2017-01-17 19:02
Blocked by projecthydra/sufia#2970.

**Comment by atz** [comment] 2017-01-31 23:52
projecthydra-labs/hyku#580 is closed, but I don't know that it fully unblocked this.

**Comment by danhorst** [comment] 2017-02-01 14:50
Duplicate of #190

**Closed** 2017-02-01 16:25 UTC
Labels: enhancement, user interface
