### ISSUE TITLE
Depositor unable to edit work in "changes required" workflow state

### ISSUE THREAD

**Issue by laritakr** [projecthydra-labs/hyrax#920] opened 2017-05-09 14:32 UTC
### Descriptive summary

Tested branch: Hyrax 1-0-Stable branch

As the depositor, when a work is in the `changes_required` state, I can tweak binaries but I can't edit metadata.

### Rationale

When a work is returned with "changes required", the depositor is unable to make requested changes, as there is no edit option on the work. There is an option next to the file listing to edit attached files.

### Expected behavior

A depositor needs to be fully able to edit their work when in "changes_required" state.

### Actual behavior

Only a manager has the ability to fully edit the work. The depositor can view their public works, but cannot even see their private works. The depositor has no edit option.
Spreadsheet of [permissions and testing results](https://docs.google.com/spreadsheets/d/1zQsWlYMVs7gz6dHaOiXICygLj_5GTFOmbpI9MHRAq5o/edit#gid=0) on both Stable and Master branches. 

### Steps to reproduce the behavior

[The gist shows the steps taken, and the highlighted line shows the point where this issue was reached.
](https://gist.github.com/laritakr/3020bdd70609a7fc224078dca1871fd8#file-gistfile1-txt-L86-L88)

### Related work

https://github.com/projecthydra-labs/hyrax/issues/882

**Comment by jcoyne** [comment] 2017-05-09 14:57
Is this a duplicate of #857

**Comment by laritakr** [comment] 2017-05-09 15:52
Possibly... that one seems to contain several issues. I made this one to document the one specific missing feature so it didn't get lost, because it's going to be a complicated one.

**Comment by mark-dce** [comment] 2017-05-09 20:28
Marking this as a blocker for 1.0.0 since the original ticket this replaced was identified that way.

**Comment by laritakr** [comment] 2017-05-11 14:55
In the master branch, It appears that if the reviewer also has "viewing" in the permission template for the admin set, then they can see the private works in order to be able to review them.  So there have been some changes which could potentially be ported to the stable branch in order to make this feature work.

**Closed** 2017-05-11 22:34 UTC
Labels: backport needed, blocker, bug, in progress, mediated deposit / workflow

**Comment by mjgiarlo** [comment] 2017-05-11 22:43
Backport here: https://github.com/projecthydra-labs/hyrax/pull/957
